### ISSUE TITLE
Message: Interface/AddOns/Keystone-Companion/ui.lua:518: attempt to index local 'row' (a nil value)

### ISSUE THREAD

**Issue by Thekinghim** [kaelonR/keystone-companion#10]
Same here `Message: Interface/AddOns/Keystone-Companion/ui.lua:518: attempt to index local 'row' (a nil value)
Time: Thu Apr  4 12:52:40 2024
Count: 26
Stack: Interface/AddOns/Keystone-Companion/ui.lua:518: attempt to index local 'row' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Keystone-Companion/ui.lua"]:518: in function `RerenderPlayerRow'
[string "@Interface/AddOns/Keystone-Companion/ui.lua"]:584: in function `Rerender'
[string "@Interface/AddOns/Keystone-Companion/main.lua"]:55: in function <Interface/AddOns/Keystone-Companion/main.lua:11>

Locals: (*temporary) = <function> defined =[C]:-1`

**Comment by kaelonR** [comment]
Fixed in Beta 2.
