### ISSUE TITLE
display best dungeons for the current tyrannical/fortified week

### ISSUE THREAD

**Issue by kaelonR** [kaelonR/keystone-companion#27]
Split from #18:

> Also, it would be cool if holding alt or some other mod keybind would display best dungeons for the current tyrannical/fortified week in this tooltip

> https://imgur.com/a/TdkreBi

> Not sure if that's possible but it would help in making decisions for what key to go to next.

**Comment by Larsj02** [comment]
Sure is possible and shouldn't be hard
https://warcraft.wiki.gg/wiki/API_C_MythicPlus.GetWeeklyBestForMap

**Comment by Larsj02** [comment]
```lua
local maps = C_ChallengeMode.GetMapTable()
for _, mapID in ipairs(maps) do
   local duration, level = C_MythicPlus.GetWeeklyBestForMap(mapID)
   if duration then
      local name = C_ChallengeMode.GetMapUIInfo(mapID)
      print(string.format("+%d %s in %s", level, name, SecondsToTime(duration)))
   end
end
```


![image](https://github.com/kaelonR/keystone-companion/assets/52138902/408e70c8-8588-44a3-a1ae-2768f64bc626)
