### ISSUE TITLE
Dungeon packs

### ISSUE THREAD

**Issue by Thekinghim** [kaelonR/keystone-companion#47]
I just looked at the reddit post and a lot of people write stuff like they won't download cause it won't replace existing Addons or weakauras.

For the Weakauras point you should always reply that WeakAuras has visual functionality but it's in no way recommended to add stuff like clickables as that can break the whole UI.

For replacing stuff, we could maybe make something like these big dungeon packs with all these bars and icons and helper stuff like automatically clicking rp skips

**Comment by Larsj02** [comment]
When we add stuff like this we should probably add similar options
