### ISSUE TITLE
 Interface/AddOns/Keystone-Companion/ui.lua:521: bad argument #1 to 'unpack' (table expected, got nil)

### ISSUE THREAD

**Issue by Thekinghim** [kaelonR/keystone-companion#9]
Everytime someone joins the group this errors pops up

`Message: Interface/AddOns/Keystone-Companion/ui.lua:521: bad argument #1 to 'unpack' (table expected, got nil)
Time: Thu Apr  4 12:49:31 2024
Count: 1
Stack: Interface/AddOns/Keystone-Companion/ui.lua:521: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `unpack'
[string "@Interface/AddOns/Keystone-Companion/ui.lua"]:521: in function `RerenderPlayerRow'
[string "@Interface/AddOns/Keystone-Companion/ui.lua"]:584: in function `Rerender'
[string "@Interface/AddOns/Keystone-Companion/main.lua"]:71: in function <Interface/AddOns/Keystone-Companion/main.lua:11>

Locals: (*temporary) = <function> defined =[C]:-1`

**Comment by kaelonR** [comment]
Fixed in Beta 2.
